README.md, package.json, prisma/seed.ts
The current setup flow may result in a few errors related to Cypress that we can avoid (at least initially) by removing the test process from the setup script. This PR updates related scripts and updates the README with a bit more nuance during this phase.
=> Tweak setup scripts and update the `README`

app/routes/notes/new.tsx
Fixed non-matching id's aria-errormessage and id.
Also see https://github.com/remix-run/indie-stack/pull/36 and https://github.com/remix-run/grunge-stack/pull/38
=> fix: fixed typo in id for aria error messages

app/routes/healthcheck.tsx
Same as @DaCurse did in https://github.com/remix-run/indie-stack/pull/38
=> fix: omit path and query string from healthcheck route

mocks/index.js, mocks/start.ts
using ts-node / esbuild-requires messes with the module resolution and causes stack traces to break
=> chore: move msw to js to remove ts-node from our process

.github/workflows/deploy.yml
Addresses an issue affecting all new github repositories where styfle/cancel-workflow-actions step fails without explicit permissions on the workflow
@mcansh thanks for pointing this out
=> Add explicit github workflow permissions (similar to indie-stack PR #82)

fly.toml
As emitted by VSCode's [Even Better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml) extension, as recommended by [Fly.io](https://fly.io/docs/reference/configuration/).
=> fix: `fly.toml` invalid types

.gitpod.Dockerfile, .gitpod.yml, README.md
I've added Gitpod support to the Blue Stack (here is a similar PR for the Indie Stack https://github.com/remix-run/indie-stack/pull/58)
When a user clicks the Gitpod button, they'll get a workspace with the environment variables set, Fly pre-installed, and the Postgres database running in Docker Compose ready to go. The application starts immediately and a user can create an account and add notes right away.
cc @MichaelDeBoey https://github.com/remix-run/indie-stack/pull/58#issuecomment-1102364419
You can test this workflow by clicking this button:
[![Gitpod Ready-to-Code](https://img.shields.io/badge/Gitpod-Ready--to--Code-blue?logo=gitpod)](https://gitpod.io/#https://github.com/jacobPARIS/blues-stack/)
=> Configure Gitpod for one-click quickstart

package.json
See #78 
The problem is that the build command is only transpiling `server.ts`, whereas we want it to transpile `server.ts` and any files in the project that are referenced by `server.ts`.
=> fix(build): transpile local files referenced by server.ts

README.md
there's been a few PRs/issues across the official stacks about missing .env files and i haven't heard back whether or not these folks have opted out of the CLI installing deps for them to be certain, but perhaps we add an explicit step about it just in case
=> chore: add note about running remix init if you skip installing deps

app/routes/index.tsx
the classname `.lg:pb-18` doesn't exist in tailwind's default spacing scale. hence why it was being ordered before `.relative`
this replaces it with `.lg:pb-20`
=> replace `.lg:pb-18` with a valid classname

cypress/support/create-user.ts, cypress/support/delete-user.ts, test/setup-test-env.ts
Signed-off-by: Logan McAnsh <logan@mcan.sh>
=> chore: remove installGlobals deep import from @remix-run/node

README.md
Super minimal change since I spent a bunch of time tracking this issue down and [Kent welcomed the PR](https://github.com/remix-run/blues-stack/issues/32#issuecomment-1079201097).
Just adding a note that you'll probably want to check the `fly.toml`'s `app` variable.
=> Add note in readme about fly.io app name mismatch

package.json
Just getting ahead of this: Vitest v0.22.0 [now requires](https://github.com/vitest-dev/vitest/releases/tag/v0.22.0) that the `@vitest/coverage-c8` peer dependency also be installed if running with coverage, or it will fail.
=> chore(deps): upgrade vitest and add @vitest/coverage-c8 dev dep

cypress/support/delete-user.ts
Something about how the windows prisma client works prevents the script from exiting on windows casuing the cypress e2e tests to hang. Explictly disconnecting the prisma client allows the script to exit.
=> Fix delete user command hang on windows

.github/dependabot.yml, remix.init/index.js
Just like https://github.com/remix-run/indie-stack/pull/153
=> chore: enable Dependabot for GitHub Actions

package.json
Fixes an issue with MSW  (
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib' is not defined by "exports" in <home directory>/node_modules/headers-polyfill/package.json)
MSW recent release [0.47.3](https://github.com/mswjs/msw/pull/1407) fixes the issue.
=> fix: update `msw`

fly.toml, package.json, server.ts
Since fly.io now offers Grafana instance (https://fly-metrics.net) it could be useful to add metrics to the stack
=> feat: add Fly/Grafana metrics

server.ts
There was an issue in the configuration of the prometheus middleware. It would only measure the middleware itself. 
This fix actually configures it to measure the express `app` and expose `/metrics` on different port
=> fix(metrics): track actual `app` endpoints

package.json
Apparently we need to add the `-p` flag when running `tsc` on the `cypress` folder
https://github.com/remix-run/blues-stack/actions/runs/3951125579/jobs/6764576532
=> fix: fix `typecheck` script

.github/workflows/deploy.yml
A recent change to the build-runner breaks deployment.
https://community.fly.io/t/deploying-to-fly-via-github-action-failing/10171/19
=> fix: Update docker build step to use older builder

package.json, server.ts
The express-prometheus-middleware is no longer maintained, and it has an optional dependency on gc-stats (also abandoned), which pulls in outdated and insecure versions of several modules, causing npm audit and other security checkers to complain.
This replaces express-prometheus-middleware with a fork that does not pull in the insecure dependencies.
A better solution would be to replace the module entirely with another prometheus implementation, but this at least avoids the security issue in as unobtrusive a manner as possible, so while not the ideal fix, it is an improvement.
=> fix: opt out of known-vulnerable dependency

app/routes/_index.tsx
Pedantic fix to the accuracy of the alt tag on the hero image.
=> fix: correct cover image `alt` tag

README.md, app/db.server.ts
New versions of `flyctl`, when running `fly postgres attach`, use [flycast](https://fly.io/docs/reference/private-networking/#flycast-private-load-balancing) URLs to connect to the DB. This provides the same geo-aware load balancing that the stack already achieves today by prefixing the hostname with the region. Flycast doesn't support region prefixes. This has been causing failures for new apps.
For example:
Old: `postgres://top2.nearest.of.my-postgres.internal`
New: `postgres://my-postgres.flycast`
The old format supports a region prefix, but the new one does not.
Fixes #182
=> fix: don't add `FLY_REGION` prefix when using recent `flyctl` version

README.md
Minor docs links fixes, I think these are the correct pages, couldn't find any that suited better.
=> docs: fix fly.io links
