remix-run/blues-stack

- .eslintrc.js
> feat: extend `@remix-run/eslint-config/jest` ESLint config

- package.json
> fix: eslint caching

- app/models/note.server.ts
- app/models/user.server.ts
Inspired by @joematune's PR in the Grunge stack (https://github.com/remix-run/grunge-stack/pull/22)
> feat: make models more type-safe

- .eslintrc.js
Something seemed off when I read this comment (nitpick). 🙂
> chore: reword comment

- app/entry.client.tsx
- app/entry.server.tsx
- app/root.tsx
- app/routes/healthcheck.tsx
- app/routes/index.tsx
- app/routes/join.tsx
- app/routes/login.tsx
- app/routes/logout.tsx
- app/routes/notes.tsx
- app/routes/notes/$noteId.tsx
- app/routes/notes/index.tsx
- app/routes/notes/new.tsx
- app/session.server.ts
- app/utils.ts
- package-lock.json
- package.json
See https://github.com/remix-run/remix/pull/2430
> chore: run `replace-remix-imports` migration

- app/session.server.ts
Hey!
I was playing around with this stack and saw that only some functions have explicit return types in `session.server.tsx` so I added them.
Thanks for remix:)
> Add explicit function return types to session.server.tsx

- cypress/support/create-user.ts
> fix(cypress): use a real url when making a request

- remix.config.js
Follow-up of https://github.com/remix-run/remix/pull/2739 & https://github.com/remix-run/remix/pull/2869
> chore: ignore dotfiles in route subdirectories too

- app/session.server.ts
> fix: make Session functions more type-safe

- package.json
See remix-run/indie-stack#109 & remix-run/indie-stack#110
> chore: update `setup` script

- README.md
> docs(README): Update fly create to fly apps create

- .npmrc
- Dockerfile
> chore: add npmrc with legacy-peer-deps

- app/root.tsx
- app/routes/healthcheck.tsx
- app/routes/join.tsx
- app/routes/login.tsx
- app/routes/logout.tsx
- app/routes/notes.tsx
- app/routes/notes/$noteId.tsx
- app/routes/notes/new.tsx
Here's a pr to use the new loader inference.
Just shooting my shot, but I'm a massively huge fan of everything Remix. I'm currently in my 2nd year of University studying computer science and I'm still looking for an internship for the month of September. I would love to be an asset and help doing any kind of work for the Remix team. (Will do documentation, examples, release notes or whatever other kind of maintanence work may be needed)
I can be reached on moishinetzer@gmail.com I'm super happy to set up a call or anything it would be a dream come true to help contribute to this awesome project!
> add loader inference

- README.md
fly changed the args for attaching postgres to an app 
https://fly.io/docs/reference/postgres/#attaching-an-app-to-a-postgres-app
closes #106
> chore: update fly postgres attach command

- .eslintrc.js
- .github/workflows/deploy.yml
- cypress/support/commands.ts
- cypress/support/create-user.ts
- cypress/support/delete-user.ts
- package.json
- prisma/seed.ts
- remix.init/index.js
- remix.init/package.json
- vitest.config.ts
Just like https://github.com/remix-run/indie-stack/pull/127
> feat: remove all TypeScript references when `isTypeScript` is passed as `false` to `remix.init`

- app/routes/index.tsx
Just like @amirhossein-shakeri did in https://github.com/remix-run/indie-stack/pull/151
> fix(ui): use `object-contain` for logos

- README.md
> chore: update gitpod url

- package.json
- tailwind.config.js
- tailwind.config.ts
[ESM & TS support is now officially released](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-typescript-support)! 🥳🎉
> chore: update `tailwindcss` version

- fly.toml
- scripts/migrate.sh
> use swap space for running migrations

- remix.config.js
See https://github.com/remix-run/blues-stack/actions/runs/4904042984/jobs/8756849347#step:6:72
> chore: silence V2 warnings

- cypress/tsconfig.json
- https://github.com/cypress-io/cypress/issues/26930#issuecomment-1602799361
- https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfigjson
---
Closes #190
> fix: fix Cypress typecheck

- package.json
- server.ts
See https://github.com/remix-run/remix/pull/7009 & https://github.com/remix-run/remix/pull/7010
> chore: install `source-map-support`

- package.json
Regression in Cypress with using `Cypress.Command.add`
> fix: use exact Cypress version

- Dockerfile
This should have been in #207 🙈
---
Closes #209
> fix: update Node version in `Dockerfile`

- .github/workflows/deploy.yml
- .gitpod.yml
- package.json
https://docs.docker.com/compose/migrate
---
Closes #129
> fix: use Docker `compose` v2

- server.ts
> chore: update server.ts to watch version.txt

- server.ts
Just like @mcansh's remix-run/remix#7078
> fix: dynamically import `chokidar` so it doesn't crash production

- server.ts
See @ngbrown's remix-run/remix#7544
---
Fixes #224
Fixes #226
> fix: use reloaded build in requests

- package.json
See @xHomu's remix-run/remix#7620
> fix: restart server on server changes

- fly.toml
- scripts/migrate.sh
> feat: set swapfile size in `fly.toml`

- fly.toml
> fix: fix Fly OOM issue
